theme: jekyll-theme-tactile
title: Welcome to the Moth Classifier
description: An embedded system that takes images of moths, classifies their species, and measures their sizes
link: https://github.com/gw-cs-sd/sd-20-bajwa-khan-montgomery
video: https://www.youtube.com/embed/ZHwfJL2Lank
